task: detection

num_classes: 3
remap_mscoco_category: True

train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: "E:\nosave\Python\Foosball\src\training\dataset\XStadiumShotsSegmentation.v3i.coco\train"
    ann_file: "E:\nosave\Python\Foosball\src\training\dataset\XStadiumShotsSegmentation.v3i.coco\train\_annotations.coco.json"
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 8
  num_workers: 4
  drop_last: True 


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: "E:\nosave\Python\Foosball\src\training\dataset\XStadiumShotsSegmentation.v3i.coco\valid"
    ann_file: "E:\nosave\Python\Foosball\src\training\dataset\XStadiumShotsSegmentation.v3i.coco\valid\_annotations.coco.json"
    transforms:
      type: Compose
      ops: ~ 

  shuffle: False
  batch_size: 8
  num_workers: 4
  drop_last: False